#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "T10 — Oracle Cloud Account & Instance Provisioning"

# ── Stage 1: Always Free account signup ────────────────────────────────────
stage "Oracle Cloud — Always Free signup"
say "GitHub issue #10 needs an Oracle Cloud account before anything else can happen."
say "Identity verification (a card for fraud-check only, on the Always Free tier no"
say "charge should occur) is part of signup — only you can do this step."
open_url "https://signup.oraclecloud.com/"
step "Fill in country/name/email, verify the email, then complete phone + card"
step "verification. Pick a home region close to wherever the app calls the"
step "instance from — you can't change the home region later."
pause "Press Enter once the account is created and you're at the OCI Console."
confirm "Account active and you're logged into the Console?" || warn "come back to this stage once it is — re-run the wizard, it's idempotent."

# ── Stage 2: Create the Ampere A1 compute instance ─────────────────────────
stage "Create the Ampere A1 instance"
say "Always Free includes up to 4 OCPUs / 24GB RAM total across Ampere A1 shapes."
say "We'll use it all on one box: 4 OCPU, 24GB RAM, Ubuntu 24.04."
open_url "https://cloud.oracle.com/compute/instances/create"
step "Name: e.g. platypus-ollama. Image: change image → Ubuntu → 24.04."
step "Shape: change shape → Ampere → VM.Standard.A1.Flex → 4 OCPU / 24GB."
step "Networking: let it create a new VCN (or reuse one) — default public subnet is fine,"
step "we'll lock the firewall down to Ollama's port in the next stage."
step "SSH keys: choose 'Generate a key pair for me' and download BOTH the private and"
step "public key now — OCI only shows the private key once."
note "If you already downloaded a keypair, note the private key's local path for stage 4."
pause "Press Enter once you've clicked Create and the instance shows RUNNING."
step "On the instance's detail page, copy the Public IP address."
ask ORACLE_INSTANCE_IP "Paste the instance's public IP:"
ask ORACLE_SSH_KEY_PATH "Local path to the downloaded private key (e.g. ~/Downloads/ssh-key.key):"

# ── Stage 3: Lock down the firewall to Ollama's port only ──────────────────
stage "Security list — open 11434, not to the world"
say "Ollama listens on 11434. It must NOT be reachable from the public internet —"
say "only from wherever OLLAMA_BASE_URL gets called from (this app's server egress)."
note "If you don't know that egress CIDR yet (e.g. Vercel's fixed IPs aren't set up),"
note "the safest default for now is your own current IP/32 for testing, then narrow"
note "or widen it later once the calling environment's egress range is known."
open_url "https://cloud.oracle.com/networking/vcns"
step "Open your instance's VCN → the subnet's Security List (or an attached NSG)."
step "Add Ingress Rule: source CIDR = the range below, IP Protocol = TCP,"
step "Destination Port Range = 11434."
ask ORACLE_ALLOWED_SOURCE_CIDR "Source CIDR to allow into port 11434 (never 0.0.0.0/0):"
if [[ "$ORACLE_ALLOWED_SOURCE_CIDR" == "0.0.0.0/0" ]]; then
  warn "0.0.0.0/0 exposes Ollama to the entire internet — T10's DoD explicitly rules this out."
  confirm "Really proceed with a public-facing rule?" || { warn "go back and narrow the CIDR before continuing."; exit 1; }
fi
step "Also confirm the instance's own OS firewall (iptables/ufw) doesn't block 11434 —"
step "Ubuntu 24.04 cloud images usually ship with none active, but worth checking once"
step "Ollama is installed in T11."
pause "Press Enter once the ingress rule is saved."

# ── Stage 4: Verify SSH access ──────────────────────────────────────────────
stage "Verify SSH access"
say "Confirms T11's follow-up ticket will actually be able to reach the box."
note "Testing: ssh -i \"$ORACLE_SSH_KEY_PATH\" -o ConnectTimeout=8 -o StrictHostKeyChecking=accept-new ubuntu@$ORACLE_INSTANCE_IP 'echo ok'"
if ssh -i "$ORACLE_SSH_KEY_PATH" -o ConnectTimeout=8 -o StrictHostKeyChecking=accept-new "ubuntu@$ORACLE_INSTANCE_IP" 'echo ok' >/dev/null 2>&1; then
  printf '  %s✓ SSH reachable%s as ubuntu@%s\n' "$GREEN" "$RESET" "$ORACLE_INSTANCE_IP"
else
  warn "couldn't SSH in yet — check the key path, that the instance finished booting,"
  warn "and that your own IP is allowed on port 22 in the security list. Not fatal:"
  warn "you can retry manually before handing this off to T11."
  SKIPPED+=("verify SSH to ubuntu@$ORACLE_INSTANCE_IP with $ORACLE_SSH_KEY_PATH")
fi

# ── Stage 5: Record the endpoint locally ────────────────────────────────────
stage "Save the endpoint"
say "T11 will install Ollama on this box under OLLAMA_MODEL=qwen2.5-coder-platypus:3b."
say "Ollama isn't running yet, so OLLAMA_BASE_URL will 404 until T11 lands — but wiring"
say "it into .env now means lib/ollama.ts's config is ready the moment T11 finishes."
write_env OLLAMA_BASE_URL "http://$ORACLE_INSTANCE_IP:11434"
note "OLLAMA_MODEL is already set to qwen2.5-coder-platypus:3b in .env.example; leave it."

# ── Stage 6: Resolution comment for GitHub issue #10 ────────────────────────
stage "Record the resolution on issue #10"
say "T10's Definition of Done wants the endpoint + access pointer on the issue —"
say "pointers only, never the private key or any secret itself."
COMMENT="Oracle Cloud Always Free account provisioned. Ampere A1 instance running (4 OCPU / 24GB, Ubuntu 24.04), reachable via SSH as ubuntu@${ORACLE_INSTANCE_IP}. Security list restricts inbound 11434 to ${ORACLE_ALLOWED_SOURCE_CIDR} only. SSH private key held locally by the human, not committed/pasted — hand off via your team's secrets manager for T11. Endpoint for T11/T12: http://${ORACLE_INSTANCE_IP}:11434"
printf '\n  %sComment to post:%s\n' "$BOLD" "$RESET"
printf '  %s\n\n' "$COMMENT"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if confirm "Post this as a comment on issue #10 now?"; then
    if gh issue comment 10 --body "$COMMENT" >/dev/null 2>&1; then
      printf '  %s✓ posted%s to issue #10\n' "$GREEN" "$RESET"
    else
      SKIPPED+=("post resolution comment on issue #10 (gh issue comment 10 failed)")
      warn "gh issue comment failed — paste the text above manually."
    fi
  else
    SKIPPED+=("post resolution comment on issue #10 (paste the text above manually)")
  fi
else
  SKIPPED+=("post resolution comment on issue #10 — gh not ready, paste the text above manually")
fi

finish
